DROP DATABASE IF EXISTS TRANSPORTADORA
CREATE DATABASE TRANSPORTADORA;
GO

USE TRANSPORTADORA;
GO

CREATE TABLE ENDERECO
(
	 ENDERECOID		INT				NOT NULL IDENTITY(10000000, 1)
	,CEP			VARCHAR(8)		NOT NULL
	,LOGRADOURO		VARCHAR(200)	NOT NULL
	,NUMERO			VARCHAR(20)		NOT NULL
	,BAIRRO			VARCHAR(200)	NOT NULL
	,CIDADE			VARCHAR(200)	NOT NULL
	,ESTADO			VARCHAR(200)	NOT NULL
	,PAIS			VARCHAR(200)	NOT NULL
	,ATIVO			BIT				NOT NULL
	,DATACADASTRO	DATETIME		NOT NULL

	CONSTRAINT PK_ENDERECOID PRIMARY KEY(ENDERECOID)
);

CREATE TABLE REMETENTE
(
	 REMETENTEID	INT				NOT NULL IDENTITY(10000000, 1)
	,RAZAOSOCIAL	VARCHAR(200)	NOT NULL
	,EMPRESA		BIT				NOT NULL
	,CNPJ			VARCHAR(14)
	,CPF			VARCHAR(11)
	,ENDERECOID		INT				NOT NULL
	,ATIVO			BIT				NOT NULL
	,DATACADASTRO	DATETIME		NOT NULL

	CONSTRAINT PK_REMETENTEID PRIMARY KEY(REMETENTEID)

	CONSTRAINT FK_REMETENTE_ENDERECOID FOREIGN KEY(ENDERECOID)
	REFERENCES ENDERECO(ENDERECOID)
);

CREATE TABLE DESTINATARIO
(
	 DESTINATARIOID		INT				NOT NULL IDENTITY(10000000, 1)
	,RAZAOSOCIAL		VARCHAR(200)	NOT NULL
	,EMPRESA			BIT				NOT NULL
	,CNPJ				VARCHAR(14)
	,CPF				VARCHAR(11)
	,ENDERECOID			INT				NOT NULL
	,ATIVO				BIT				NOT NULL
	,DATACADASTRO		DATETIME		NOT NULL

	CONSTRAINT PK_DESTINATARIOID PRIMARY KEY(DESTINATARIOID)

	CONSTRAINT FK_DESTINATARIO_ENDERECOID FOREIGN KEY(ENDERECOID)
	REFERENCES ENDERECO(ENDERECOID)
);

CREATE TABLE ITEMS
(
	 ITEMID			INT				NOT NULL	IDENTITY(10000000, 1)
	,CODIGO			VARCHAR(200)	NOT NULL
	,DESCRICAO		VARCHAR(200)	NOT NULL
	,QUANTIDADE		INT				NOT NULL
	,PRECO			MONEY			NOT NULL
	,ATIVO			BIT				NOT NULL
	,DATACADASTRO	DATETIME		NOT NULL

	CONSTRAINT PK_ITEMID PRIMARY KEY(ITEMID)
);

CREATE TABLE PEDIDO
(
	 PEDIDOID			INT			NOT NULL	IDENTITY(10000000, 1)
	,REMETENTEID		INT			NOT NULL
	,DESTINATARIOID		INT			NOT NULL
	,ATIVO				BIT			NOT NULL
	,DATACADASTRO		DATETIME	NOT NULL

	CONSTRAINT PK_PEDIDOID PRIMARY KEY(PEDIDOID)

	CONSTRAINT FK_PEDIDO_REMENTENTEID FOREIGN KEY(REMETENTEID)
	REFERENCES REMETENTE(REMETENTEID),

	CONSTRAINT FK_PEDIDO_DESTINATARIOID FOREIGN KEY(DESTINATARIOID)
	REFERENCES DESTINATARIO(DESTINATARIOID)
);

CREATE TABLE PEDIDO_ITEMS
(
	 PEDIDO_ITEMID		INT			NOT NULL	IDENTITY(10000000, 1)
	,PEDIDOID			INT			NOT NULL
	,ITEMID				INT			NOT NULL
	,ATIVO				BIT			NOT NULL
	,DATACADASTRO		DATETIME	NOT NULL

	CONSTRAINT PK_PEDIDO_ITEMID PRIMARY KEY(PEDIDO_ITEMID)

	CONSTRAINT FK_PEDIDO_PEDIDOID FOREIGN KEY(PEDIDOID)
	REFERENCES PEDIDO(PEDIDOID),

	CONSTRAINT FK_PEDIDO_ITEMID FOREIGN KEY(ITEMID)
	REFERENCES ITEMS(ITEMID)
);

CREATE TABLE OCORRENCIA
(
	 OCORRENCIAID	INT				NOT NULL	IDENTITY(10000000, 1)
	,DESCRICAO		VARCHAR(200)	NOT NULL
	,ATIVO			BIT				NOT NULL
	,DATACADASTRO	DATETIME		NOT NULL

	CONSTRAINT PK_OCORRENCIAID PRIMARY KEY(OCORRENCIAID)
);

CREATE TABLE OCORRENCIA_PEDIDO
(
	 OCORRENCIA_PEDIDOID	INT			NOT NULL	IDENTITY(10000000, 1)
	,PEDIDOID				INT			NOT NULL
	,OCORRENCIAID			INT			NOT NULL
	,ATIVO					BIT			NOT NULL
	,DATACADASTRO			DATETIME	NOT NULL

	CONSTRAINT PK_OCORRENCIA_PEDIDOID PRIMARY KEY(OCORRENCIAID)

	CONSTRAINT FK_OCORRENCIA_PEDIDO_PEDIDOID FOREIGN KEY(PEDIDOID)
	REFERENCES PEDIDO(PEDIDOID),

	CONSTRAINT FK_OCORRENCIA_OCORRENCIA_PEDIDOID FOREIGN KEY(OCORRENCIAID)
	REFERENCES OCORRENCIA(OCORRENCIAID)
);

CREATE TABLE LOGS
(
	 LOGID			INT				NOT NULL		IDENTITY(10000000, 1)
	,JSON_ENTRADA	VARCHAR(MAX)	NOT NULL
	,MENSAGEM		VARCHAR(200)	NOT NULL
	,ATIVO			BIT				NOT NULL
	,DATACADASTRO	DATETIME		NOT NULL

	CONSTRAINT PK_LOGID PRIMARY KEY(LOGID)
);